version: '3.8'

services:
  app:
    build: .
    container_name: couponservice
    ports:
      - '3002:3002'
    environment:
      - DATABASE_URL=postgresql://coupon-user:123@coupon-db:5432/coupon-db?schema=public
    depends_on:
      - db
    networks:
      - shared-network

  db:
    image: postgres:16-alpine
    container_name: coupon-db
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=coupon-user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=coupon-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-network
volumes:
  postgres_data:
  
networks:
  shared-network:
    external: true
